name: "static analysis"

on:
    pull_request: ~
    push: ~
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 5 * *"

jobs:
    static-analysis:
        name: "static analysis"
        runs-on: "ubuntu-latest"
        steps:
            - name: "checkout"
              uses: "actions/checkout@v4"

            - name: "build the environment"
              run: "dev/bin/docker-compose build"

            - name: "install dependencies"
              run: "dev/bin/php composer update --prefer-stable"

            - name: "run static analysis"
              run: "dev/bin/php psalm --shepherd --stats"

            - name: clear docker volumes
              if: ${{ always() }}
              run: dev/bin/docker-compose down --volumes
